Update test-coverage.yml

diff --git a/.github/workflow.github/workflows/test-coverage.yml b/.github/workflow.github/workflows/test-coverage.yml
--- a/.github/workflow.github/workflows/test-coverage.yml
+++ b/.github/workflow.github/workflows/test-coverage.yml
@@ -4,7 +4,7 @@ on:
   pull_request:
   push:
     branches:
-      - '*' # Asegura que se ejecute en la rama principal
+      - '**/*.md' # Asegura que se ejecute en la rama principal
 
 jobs:
   coverage:
@@ -13,25 +13,45 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
-          fetch-depth: 10  # Necesario para encontrar notas previas de cobertura
-
-      - name: Set up Go
+          fetch-depth: 10 # Necesario para encontrar notas previas de cobertura
+    
+     - name: Set up Go
         uses: actions/setup-go@v4
         with:
-          go-version: stable  # Usa la versión estable de Go
+          go-version:1.20  # Usa la versión estable de Go
+          run: |
+            go mod download
+            go get -u golang.org/x/lint/golint
+            go get -t .
 
-      - name: Run Go tests with coverage
+    - name: Lint
+         run: |
+         golint -set_exit_status ./...
+
+    - name: Vet
+         run: |
+         go vet ./...      
+
+    - name: Unit tests
         run: |
-          go test -covermode=count -coverprofile=coverage.out ./...
-          go tool cover -html=coverage.out -o coverage.html
-        # Este paso genera los archivos `coverage.out` y `coverage.html`
+            sudo go test ./... -coverprofile coverage.out -covermode count
+            sudo go tool cover -func coverage.out
 
-      - name: Archive Go Coverage Report
-        uses: actions/upload-artifact@v4
-        with:
-          name: go-coverage-report
-          path: coverage.html  # Asegúrate de que el archivo de cobertura se haya generado correctamente
+    - name: Quality Gate - Test coverage shall be above threshold
+        env:
+          TESTCOVERAGE_THRESHOLD: 90
+        run: |
+             echo "Quality Gate: checking test coverage is above threshold ..."
+             echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
+             totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+             echo "Current test coverage : $totalCoverage %"
+             if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 < $2)}') )); then
+                echo "OK"
+            else
+                echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+                echo "Failed"
+                exit 1
+             fi     
 
-      - name: Debug working directory
+    - name: Debug working directory
         run: ls -la  # Verificar en qué directorio estamos
-
